### ISSUE TITLE
Children of grid system

### ISSUE THREAD

**Issue by starryeyez024** [redhataccess/cp-grid#1]
If all the children just have one class and it's always the same, consider using > * to apply styles to children rather than classes. That way you can adjust one class on the parent and not have to fuss with children classes. 

```css
[data-cp-grid="sm-2 md-4"] {
  > * {
    width: ...
   }
}
```

**Comment by starryeyez024** [comment]
Usually you don't need to change the grid itself (from 12 to 6) for example, since you can express the same widths on a 12 column grid that you can on a 6 col grid. I do like how you are expressing what the different layouts are at various breakpoints like sm-2 and md-4, but how does this work for uneven grids? sm-6-6 med-8-4 ?

**Comment by starryeyez024** [comment]
line 37 of cp-grid.scss, how do you know for sure that the .cp-grid-item always has a border?

**Comment by starryeyez024** [comment]
sidenote, check out:
- bit.ly/layout-styles
- http://bit.ly/mixin-layouts 
:)

**Comment by markcaron** [comment]
Yeah, good point. I'll update this.

**Comment by markcaron** [comment]
The border is used as a placeholder for column/cards with borders.
