### ISSUE TITLE
Why redefine base grid?

### ISSUE THREAD

**Issue by starryeyez024** [redhataccess/cp-grid#2]
Usually you don't need to change the grid itself (from 12 to 6) for example, since you can express the same widths on a 12 column grid that you can on a 6 col grid. I do like how you are expressing what the different layouts are at various breakpoints like sm-2 and md-4, but how does this work for uneven grids? sm-6-6 med-8-4 ?

**Comment by markcaron** [comment]
I changed the syntax a bit, which may be what's confusing. "sm-2" denotes a grid of 2 columns, not six columns that span 2 each. I think I'll switch this up. "sm-2-cols" should denote a grid of 2 columns. This may be more clear. I'll remove the "sm-2" concept in favor of this. I'll add an addition option like "sm-2-8" which would function as expected. Thanks for the feedback.
